package kz.zholsafe.risk;

public enum RiskEvidenceType {
    OBJECT_OUTSIDE_CORRIDOR, OBJECT_NEAR_CORRIDOR, OBJECT_IN_CORRIDOR, OBJECT_CENTRAL,
    MOVING_TOWARD_CORRIDOR, PREDICTED_CORRIDOR_ENTRY, APPARENT_APPROACH, APPARENT_RECEDE,
    METRIC_DISTANCE_AVAILABLE, METRIC_CLOSING, METRIC_TTC_SHORT, IMAGE_SCALE_TTC_SHORT,
    LARGE_HAZARD_CLASS, LARGE_IN_FRAME, PHYSICAL_ESTIMATE_UNAVAILABLE,
    TRAJECTORY_UNAVAILABLE, LOW_QUALITY_EVIDENCE, PHYSICAL_LOW_QUALITY, TTC_CONFLICT
}
