package kz.zholsafe.physical;

/** Explicit evidence/failure reason; AVAILABLE is never used for an unavailable value. */
public enum PhysicalReason {
    AVAILABLE, NO_CALIBRATION, CALIBRATION_MISMATCH, INVALID_GEOMETRY, NO_SIZE_PRIOR,
    UNKNOWN_CLASS, LOW_QUALITY, TRACK_NOT_CURRENT, INSUFFICIENT_HISTORY, NOT_CLOSING,
    CONFLICTING_ESTIMATES, CROSS_TRACK_HISTORY, INVALID_TIMESTAMP, OUT_OF_RANGE, UPSTREAM_UNAVAILABLE, DISABLED
}
