#!/usr/bin/env python3
"""Export YOLO weights → models/road/<id>/model.onnx + labels.txt + model-spec.json (Stage 2).

Usage:
    # YOLO11n, raw head (NMS in the app):
    python export/export_onnx.py --weights yolo11n.pt --model-dir ../models/road/yolo11n --nms false
    # YOLO26n, end2end head (default for that family):
    python export/export_onnx.py --weights yolo26n.pt --model-dir ../models/road/yolo26n

labels.txt is taken from the checkpoint's own class names (model.names) — never from
configs/classes.yaml — so the Java LabelMap always sees the real model labels. For a custom
ZholSafe-trained checkpoint those names ARE the canonical registry order.
model-spec.json is then generated by write_model_spec.py from the real graph.

Requires the training stack (requirements-train.txt). Not runnable in environments without it;
the script exits 2 with a message and writes nothing.
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--weights", type=Path, required=True)
    parser.add_argument("--model-dir", type=Path, required=True, help="models/road/<id>/")
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--opset", type=int, default=17)
    parser.add_argument("--nms", choices=["true", "false", "default"], default="default",
                        help="Ultralytics export nms flag; 'default' leaves the family default (YOLO26: end2end)")
    parser.add_argument("--model-id", default=None)
    parser.add_argument("--family", default=None)
    parser.add_argument("--version", default="pretrained")
    args = parser.parse_args()
    if not args.weights.exists():
        print(f"weights not found: {args.weights}", file=sys.stderr)
        return 2
    try:
        from ultralytics import YOLO  # type: ignore
    except ImportError:
        print("Training stack not installed. Run: pip install -r requirements-train.txt", file=sys.stderr)
        return 2
    model = YOLO(str(args.weights))
    export_kwargs = dict(format="onnx", imgsz=args.imgsz, opset=args.opset, simplify=True, dynamic=False)
    if args.nms != "default":
        export_kwargs["nms"] = args.nms == "true"
    exported = model.export(**export_kwargs)
    args.model_dir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(exported, args.model_dir / "model.onnx")
    names = model.names  # {index: label}
    labels = [names[i] for i in range(len(names))]
    (args.model_dir / "labels.txt").write_text("\n".join(labels) + "\n", encoding="utf-8")
    model_id = args.model_id or f"zholsafe-{args.weights.stem}"
    family = args.family or "".join(ch for ch in args.weights.stem if not ch.isalpha() or ch in "yolo")
    cmd = [sys.executable, str(Path(__file__).with_name("write_model_spec.py")), "--model-dir", str(args.model_dir),
           "--model-id", model_id, "--family", family, "--version", args.version]
    print("running:", " ".join(cmd))
    return subprocess.call(cmd)


if __name__ == "__main__":
    raise SystemExit(main())
